[package]
name = "apocalipse-faxina"
version = "0.1.0"
edition = "2021"
authors = ["linuxhell"]
description = "Apocalipse Faxina - manutenção e limpeza portátil para Windows x64"
build = "build.rs"

[dependencies]
eframe = { version = "0.31.1", default-features = false, features = ["glow", "default_fonts"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging"
] }

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
